/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(perception_msgs/CenterposeNodeMessage.msg)
##################################################################################
   # An perception scene node for an ArUco marker
   # The topic name identifies the node.

   # The detectable scene node information
   perception_msgs/DetectableSceneNodeMessage detectable_scene_node

   string object_type
   int32 object_id
   float64 confidence
   geometry_msgs/Point[8] bounding_box_vertices
   geometry_msgs/Point[8] bounding_box_vertices_2d

   bool enable_tracking
##################################################################################

 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   An perception scene node for an ArUco marker
   The topic name identifies the node.
*/
public class CenterposeNodeMessage implements ROS2Message<CenterposeNodeMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::CenterposeNodeMessage_";

   /**
      The detectable scene node information
   */
   private final perception_msgs.msg.dds.DetectableSceneNodeMessage detectable_scene_node_;
   private final StringBuilder object_type_;
   private int object_id_;
   private double confidence_;
   private final geometry_msgs.msg.dds.Point[] bounding_box_vertices_;
   private final geometry_msgs.msg.dds.Point[] bounding_box_vertices_2d_;
   private boolean enable_tracking_;

   public CenterposeNodeMessage()
   {
      detectable_scene_node_ = new perception_msgs.msg.dds.DetectableSceneNodeMessage();
      object_type_ = new StringBuilder();
      bounding_box_vertices_ = new geometry_msgs.msg.dds.Point[8];
      // bounding_box_vertices is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < bounding_box_vertices_.length; ++i)
      {
         bounding_box_vertices_[i] = new geometry_msgs.msg.dds.Point();
      }
      bounding_box_vertices_2d_ = new geometry_msgs.msg.dds.Point[8];
      // bounding_box_vertices_2d is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < bounding_box_vertices_2d_.length; ++i)
      {
         bounding_box_vertices_2d_[i] = new geometry_msgs.msg.dds.Point();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += detectable_scene_node_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * object_type_.length()) + 1; // object_type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // object_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // confidence_
      for (int i = 0; i < bounding_box_vertices_.length; ++i)
      {
         currentAlignment += bounding_box_vertices_[i].calculateSizeBytes(currentAlignment);
      }
      for (int i = 0; i < bounding_box_vertices_2d_.length; ++i)
      {
         currentAlignment += bounding_box_vertices_2d_[i].calculateSizeBytes(currentAlignment);
      }
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_tracking_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      detectable_scene_node_.serialize(buffer);
      buffer.writeString(object_type_);
      buffer.writeInt(object_id_);
      buffer.writeDouble(confidence_);
      for (int i = 0; i < bounding_box_vertices_.length; ++i)
      {
         bounding_box_vertices_[i].serialize(buffer);
      }
      for (int i = 0; i < bounding_box_vertices_2d_.length; ++i)
      {
         bounding_box_vertices_2d_[i].serialize(buffer);
      }
      buffer.writeBoolean(enable_tracking_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      detectable_scene_node_.deserialize(buffer);
      buffer.readString(object_type_);
      object_id_ = buffer.readInt();
      confidence_ = buffer.readDouble();
      for (int i = 0; i < bounding_box_vertices_.length; ++i)
      {
         bounding_box_vertices_[i].deserialize(buffer);
      }
      for (int i = 0; i < bounding_box_vertices_2d_.length; ++i)
      {
         bounding_box_vertices_2d_[i].deserialize(buffer);
      }
      enable_tracking_ = buffer.readBoolean();

   }

   @Override
   public void set(CenterposeNodeMessage from)
   {
      detectable_scene_node_.set(from.detectable_scene_node_);
      object_type_.delete(0, object_type_.length());
      object_type_.insert(0, from.object_type_);
      object_id_ = from.object_id_;
      confidence_ = from.confidence_;
      for (int i = 0; i < bounding_box_vertices_.length; ++i)
      {
         bounding_box_vertices_[i].set(from.bounding_box_vertices_[i]);
      }
      for (int i = 0; i < bounding_box_vertices_2d_.length; ++i)
      {
         bounding_box_vertices_2d_[i].set(from.bounding_box_vertices_2d_[i]);
      }
      enable_tracking_ = from.enable_tracking_;

   }

   public perception_msgs.msg.dds.DetectableSceneNodeMessage getDetectableSceneNode()
   {
      return detectable_scene_node_;
   }

   public StringBuilder getObjectType()
   {
      return object_type_;
   }

   public int getObjectId()
   {
      return object_id_;
   }

   public void setObjectId(int object_id_)
   {
      this.object_id_ = object_id_;
   }

   public double getConfidence()
   {
      return confidence_;
   }

   public void setConfidence(double confidence_)
   {
      this.confidence_ = confidence_;
   }

   public geometry_msgs.msg.dds.Point[] getBoundingBoxVertices()
   {
      return bounding_box_vertices_;
   }

   public geometry_msgs.msg.dds.Point[] getBoundingBoxVertices2d()
   {
      return bounding_box_vertices_2d_;
   }

   public boolean getEnableTracking()
   {
      return enable_tracking_;
   }

   public void setEnableTracking(boolean enable_tracking_)
   {
      this.enable_tracking_ = enable_tracking_;
   }


}