/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(perception_msgs/ChunkedMapMessage.msg)
##################################################################################
   # Contains all the chunks to created the map (chunked map)
   ChunkMessage[] chunks
##################################################################################

 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class ChunkedMapMessage implements ROS2Message<ChunkedMapMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::ChunkedMapMessage_";

   /**
      Contains all the chunks to created the map (chunked map)
   */
   private final IDLObjectSequence<perception_msgs.msg.dds.ChunkMessage> chunks_;

   public ChunkedMapMessage()
   {
      chunks_ = new IDLObjectSequence<perception_msgs.msg.dds.ChunkMessage>(perception_msgs.msg.dds.ChunkMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += chunks_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      chunks_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      chunks_.deserialize(buffer);

   }

   @Override
   public void set(ChunkedMapMessage from)
   {
      chunks_.set(from.chunks_);

   }

   public IDLObjectSequence<perception_msgs.msg.dds.ChunkMessage> getChunks()
   {
      return chunks_;
   }


}