/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(perception_msgs/PolygonizerParametersStringMessage.msg)
##################################################################################
   # String serialized polygonizer parameters
   # Might be kinda long, so give it some space

   string[<=2056] parameters

##################################################################################

 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   String serialized polygonizer parameters
   Might be kinda long, so give it some space
*/
public class PolygonizerParametersStringMessage implements ROS2Message<PolygonizerParametersStringMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::PolygonizerParametersStringMessage_";

   private final IDLStringSequence parameters_;

   public PolygonizerParametersStringMessage()
   {
      parameters_ = new IDLStringSequence(2056);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += parameters_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      parameters_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      parameters_.deserialize(buffer);

   }

   @Override
   public void set(PolygonizerParametersStringMessage from)
   {
      parameters_.set(from.parameters_);

   }

   public IDLStringSequence getParameters()
   {
      return parameters_;
   }


}