/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(perception_msgs/TerrainMapMessage.msg)
##################################################################################
   # This message is part of the IHMC height map module

   # Unique ID used to identify this message, should preferably be consecutively increasing.
   uint64 sequence_id

   # Height map message
   HeightMapMessage height_map

   # Traversability score, on a 0 to 1 scale
   float32[<=255000] traversability_score
   # Classifying traversability according to SnapResult
   byte[<=255000] traversability_class

   # The raw data for the snap normal x value, which are stored as chars.
   byte[<=255000] snapped_normal_x_data
   # The raw data for the snap normal y value, which are stored as chars.
   byte[<=255000] snapped_normal_y_data
   # The raw data for the snap normal z value, which are stored as chars.
   byte[<=255000] snapped_normal_z_data

##################################################################################

 */
package perception_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   This message is part of the IHMC height map module
*/
public class TerrainMapMessage implements ROS2Message<TerrainMapMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::TerrainMapMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Height map message
   */
   private final perception_msgs.msg.dds.HeightMapMessage height_map_;
   /**
      Traversability score, on a 0 to 1 scale
   */
   private final IDLFloatSequence traversability_score_;
   /**
      Classifying traversability according to SnapResult
   */
   private final IDLByteSequence traversability_class_;
   /**
      The raw data for the snap normal x value, which are stored as chars.
   */
   private final IDLByteSequence snapped_normal_x_data_;
   /**
      The raw data for the snap normal y value, which are stored as chars.
   */
   private final IDLByteSequence snapped_normal_y_data_;
   /**
      The raw data for the snap normal z value, which are stored as chars.
   */
   private final IDLByteSequence snapped_normal_z_data_;

   public TerrainMapMessage()
   {
      height_map_ = new perception_msgs.msg.dds.HeightMapMessage();
      traversability_score_ = new IDLFloatSequence(255000);
      traversability_class_ = new IDLByteSequence(255000);
      snapped_normal_x_data_ = new IDLByteSequence(255000);
      snapped_normal_y_data_ = new IDLByteSequence(255000);
      snapped_normal_z_data_ = new IDLByteSequence(255000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += height_map_.calculateSizeBytes(currentAlignment);
      currentAlignment += traversability_score_.calculateSizeBytes(currentAlignment);
      currentAlignment += traversability_class_.calculateSizeBytes(currentAlignment);
      currentAlignment += snapped_normal_x_data_.calculateSizeBytes(currentAlignment);
      currentAlignment += snapped_normal_y_data_.calculateSizeBytes(currentAlignment);
      currentAlignment += snapped_normal_z_data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      height_map_.serialize(buffer);
      traversability_score_.serialize(buffer);
      traversability_class_.serialize(buffer);
      snapped_normal_x_data_.serialize(buffer);
      snapped_normal_y_data_.serialize(buffer);
      snapped_normal_z_data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      height_map_.deserialize(buffer);
      traversability_score_.deserialize(buffer);
      traversability_class_.deserialize(buffer);
      snapped_normal_x_data_.deserialize(buffer);
      snapped_normal_y_data_.deserialize(buffer);
      snapped_normal_z_data_.deserialize(buffer);

   }

   @Override
   public void set(TerrainMapMessage from)
   {
      sequence_id_ = from.sequence_id_;
      height_map_.set(from.height_map_);
      traversability_score_.set(from.traversability_score_);
      traversability_class_.set(from.traversability_class_);
      snapped_normal_x_data_.set(from.snapped_normal_x_data_);
      snapped_normal_y_data_.set(from.snapped_normal_y_data_);
      snapped_normal_z_data_.set(from.snapped_normal_z_data_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public perception_msgs.msg.dds.HeightMapMessage getHeightMap()
   {
      return height_map_;
   }

   public IDLFloatSequence getTraversabilityScore()
   {
      return traversability_score_;
   }

   public IDLByteSequence getTraversabilityClass()
   {
      return traversability_class_;
   }

   public IDLByteSequence getSnappedNormalXData()
   {
      return snapped_normal_x_data_;
   }

   public IDLByteSequence getSnappedNormalYData()
   {
      return snapped_normal_y_data_;
   }

   public IDLByteSequence getSnappedNormalZData()
   {
      return snapped_normal_z_data_;
   }


}