/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(behavior_msgs/FootPoseActionStateMessage.msg)
##################################################################################
   # Parent state fields
   behavior_msgs/ActionNodeStateMessage state

   # Definition
   behavior_msgs/FootPoseActionDefinitionMessage definition
##################################################################################

 */
package behavior_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class FootPoseActionStateMessage implements ROS2Message<FootPoseActionStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::FootPoseActionStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.msg.dds.ActionNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.msg.dds.FootPoseActionDefinitionMessage definition_;

   public FootPoseActionStateMessage()
   {
      state_ = new behavior_msgs.msg.dds.ActionNodeStateMessage();
      definition_ = new behavior_msgs.msg.dds.FootPoseActionDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);

   }

   @Override
   public void set(FootPoseActionStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);

   }

   public behavior_msgs.msg.dds.ActionNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.msg.dds.FootPoseActionDefinitionMessage getDefinition()
   {
      return definition_;
   }


}