/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(controller_msgs/ContinuousStepGeneratorParametersMessage.msg)
##################################################################################
   # Message for the ContinuousStepGenerator to configure the module's parameters.
   # This module is used for controlling the walking gait using a joystick controller.

   # Unique ID used to identify this message, should preferably be consecutively increasing.
   uint64 sequence_id

   int32 number_of_footsteps_to_plan -1
   int32 number_of_fixed_footsteps -1
   float64 swing_height -1
   float64 swing_duration -1
   float64 transfer_duration -1
   float64 max_step_length -1
   float64 default_step_width -1
   float64 min_step_width -1
   float64 max_step_width -1
   float64 turn_max_angle_inward -1
   float64 turn_max_angle_outward -1
##################################################################################

 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
   Message for the ContinuousStepGenerator to configure the module's parameters.
   This module is used for controlling the walking gait using a joystick controller.
*/
public class ContinuousStepGeneratorParametersMessage implements ROS2Message<ContinuousStepGeneratorParametersMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ContinuousStepGeneratorParametersMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private int number_of_footsteps_to_plan_;
   private int number_of_fixed_footsteps_;
   private double swing_height_;
   private double swing_duration_;
   private double transfer_duration_;
   private double max_step_length_;
   private double default_step_width_;
   private double min_step_width_;
   private double max_step_width_;
   private double turn_max_angle_inward_;
   private double turn_max_angle_outward_;

   public ContinuousStepGeneratorParametersMessage()
   {
      number_of_footsteps_to_plan_ = (int) -1;
      number_of_fixed_footsteps_ = (int) -1;
      swing_height_ = (double) -1;
      swing_duration_ = (double) -1;
      transfer_duration_ = (double) -1;
      max_step_length_ = (double) -1;
      default_step_width_ = (double) -1;
      min_step_width_ = (double) -1;
      max_step_width_ = (double) -1;
      turn_max_angle_inward_ = (double) -1;
      turn_max_angle_outward_ = (double) -1;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_footsteps_to_plan_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_fixed_footsteps_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // swing_height_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // swing_duration_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // transfer_duration_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_step_length_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // default_step_width_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // min_step_width_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_step_width_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // turn_max_angle_inward_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // turn_max_angle_outward_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(number_of_footsteps_to_plan_);
      buffer.writeInt(number_of_fixed_footsteps_);
      buffer.writeDouble(swing_height_);
      buffer.writeDouble(swing_duration_);
      buffer.writeDouble(transfer_duration_);
      buffer.writeDouble(max_step_length_);
      buffer.writeDouble(default_step_width_);
      buffer.writeDouble(min_step_width_);
      buffer.writeDouble(max_step_width_);
      buffer.writeDouble(turn_max_angle_inward_);
      buffer.writeDouble(turn_max_angle_outward_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      number_of_footsteps_to_plan_ = buffer.readInt();
      number_of_fixed_footsteps_ = buffer.readInt();
      swing_height_ = buffer.readDouble();
      swing_duration_ = buffer.readDouble();
      transfer_duration_ = buffer.readDouble();
      max_step_length_ = buffer.readDouble();
      default_step_width_ = buffer.readDouble();
      min_step_width_ = buffer.readDouble();
      max_step_width_ = buffer.readDouble();
      turn_max_angle_inward_ = buffer.readDouble();
      turn_max_angle_outward_ = buffer.readDouble();

   }

   @Override
   public void set(ContinuousStepGeneratorParametersMessage from)
   {
      sequence_id_ = from.sequence_id_;
      number_of_footsteps_to_plan_ = from.number_of_footsteps_to_plan_;
      number_of_fixed_footsteps_ = from.number_of_fixed_footsteps_;
      swing_height_ = from.swing_height_;
      swing_duration_ = from.swing_duration_;
      transfer_duration_ = from.transfer_duration_;
      max_step_length_ = from.max_step_length_;
      default_step_width_ = from.default_step_width_;
      min_step_width_ = from.min_step_width_;
      max_step_width_ = from.max_step_width_;
      turn_max_angle_inward_ = from.turn_max_angle_inward_;
      turn_max_angle_outward_ = from.turn_max_angle_outward_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getNumberOfFootstepsToPlan()
   {
      return number_of_footsteps_to_plan_;
   }

   public void setNumberOfFootstepsToPlan(int number_of_footsteps_to_plan_)
   {
      this.number_of_footsteps_to_plan_ = number_of_footsteps_to_plan_;
   }

   public int getNumberOfFixedFootsteps()
   {
      return number_of_fixed_footsteps_;
   }

   public void setNumberOfFixedFootsteps(int number_of_fixed_footsteps_)
   {
      this.number_of_fixed_footsteps_ = number_of_fixed_footsteps_;
   }

   public double getSwingHeight()
   {
      return swing_height_;
   }

   public void setSwingHeight(double swing_height_)
   {
      this.swing_height_ = swing_height_;
   }

   public double getSwingDuration()
   {
      return swing_duration_;
   }

   public void setSwingDuration(double swing_duration_)
   {
      this.swing_duration_ = swing_duration_;
   }

   public double getTransferDuration()
   {
      return transfer_duration_;
   }

   public void setTransferDuration(double transfer_duration_)
   {
      this.transfer_duration_ = transfer_duration_;
   }

   public double getMaxStepLength()
   {
      return max_step_length_;
   }

   public void setMaxStepLength(double max_step_length_)
   {
      this.max_step_length_ = max_step_length_;
   }

   public double getDefaultStepWidth()
   {
      return default_step_width_;
   }

   public void setDefaultStepWidth(double default_step_width_)
   {
      this.default_step_width_ = default_step_width_;
   }

   public double getMinStepWidth()
   {
      return min_step_width_;
   }

   public void setMinStepWidth(double min_step_width_)
   {
      this.min_step_width_ = min_step_width_;
   }

   public double getMaxStepWidth()
   {
      return max_step_width_;
   }

   public void setMaxStepWidth(double max_step_width_)
   {
      this.max_step_width_ = max_step_width_;
   }

   public double getTurnMaxAngleInward()
   {
      return turn_max_angle_inward_;
   }

   public void setTurnMaxAngleInward(double turn_max_angle_inward_)
   {
      this.turn_max_angle_inward_ = turn_max_angle_inward_;
   }

   public double getTurnMaxAngleOutward()
   {
      return turn_max_angle_outward_;
   }

   public void setTurnMaxAngleOutward(double turn_max_angle_outward_)
   {
      this.turn_max_angle_outward_ = turn_max_angle_outward_;
   }


}