/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(controller_msgs/EnableHPUCommandMessage.msg)
##################################################################################
   # True to enable hydaulic power unit (HPU) and false to turn HPU off immediately (not graceful)
   bool enable_hpu

##################################################################################

 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class EnableHPUCommandMessage implements ROS2Message<EnableHPUCommandMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::EnableHPUCommandMessage_";

   /**
      True to enable hydaulic power unit (HPU) and false to turn HPU off immediately (not graceful)
   */
   private boolean enable_hpu_;

   public EnableHPUCommandMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_hpu_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(enable_hpu_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      enable_hpu_ = buffer.readBoolean();

   }

   @Override
   public void set(EnableHPUCommandMessage from)
   {
      enable_hpu_ = from.enable_hpu_;

   }

   public boolean getEnableHpu()
   {
      return enable_hpu_;
   }

   public void setEnableHpu(boolean enable_hpu_)
   {
      this.enable_hpu_ = enable_hpu_;
   }


}