/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(controller_msgs/EnableHPUStatusMessage.msg)
##################################################################################
   # True if hydaulic power unit (HPU) is enabled and false if it is turned off
   bool hpu_enabled

##################################################################################

 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class EnableHPUStatusMessage implements ROS2Message<EnableHPUStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::EnableHPUStatusMessage_";

   /**
      True if hydaulic power unit (HPU) is enabled and false if it is turned off
   */
   private boolean hpu_enabled_;

   public EnableHPUStatusMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hpu_enabled_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(hpu_enabled_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      hpu_enabled_ = buffer.readBoolean();

   }

   @Override
   public void set(EnableHPUStatusMessage from)
   {
      hpu_enabled_ = from.hpu_enabled_;

   }

   public boolean getHpuEnabled()
   {
      return hpu_enabled_;
   }

   public void setHpuEnabled(boolean hpu_enabled_)
   {
      this.hpu_enabled_ = hpu_enabled_;
   }


}