/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(controller_msgs/MasterGainScaleControllerCommandMessage.msg)
##################################################################################
   # True if this is a request to servo the robot
   # This is used to enable and ramp up the robot's controller gains, to go into freeze or stand prep
   bool servo_robot

   # True is this is a request to immediately zero the gains which can be violent and dangerous
   # This will also turn off the HPU
   bool unservo_immediately

   # True if this is a request to slowly ramp down the robot's controller gains to zero, in prepration for robot shutdown
   # This will also turn off the HPU at the end
   bool unservo_slowly

##################################################################################

 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class MasterGainScaleControllerCommandMessage implements ROS2Message<MasterGainScaleControllerCommandMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MasterGainScaleControllerCommandMessage_";

   /**
      True if this is a request to servo the robot
      This is used to enable and ramp up the robot's controller gains, to go into freeze or stand prep
   */
   private boolean servo_robot_;
   /**
      True is this is a request to immediately zero the gains which can be violent and dangerous
      This will also turn off the HPU
   */
   private boolean unservo_immediately_;
   /**
      True if this is a request to slowly ramp down the robot's controller gains to zero, in prepration for robot shutdown
      This will also turn off the HPU at the end
   */
   private boolean unservo_slowly_;

   public MasterGainScaleControllerCommandMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // servo_robot_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // unservo_immediately_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // unservo_slowly_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(servo_robot_);
      buffer.writeBoolean(unservo_immediately_);
      buffer.writeBoolean(unservo_slowly_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      servo_robot_ = buffer.readBoolean();
      unservo_immediately_ = buffer.readBoolean();
      unservo_slowly_ = buffer.readBoolean();

   }

   @Override
   public void set(MasterGainScaleControllerCommandMessage from)
   {
      servo_robot_ = from.servo_robot_;
      unservo_immediately_ = from.unservo_immediately_;
      unservo_slowly_ = from.unservo_slowly_;

   }

   public boolean getServoRobot()
   {
      return servo_robot_;
   }

   public void setServoRobot(boolean servo_robot_)
   {
      this.servo_robot_ = servo_robot_;
   }

   public boolean getUnservoImmediately()
   {
      return unservo_immediately_;
   }

   public void setUnservoImmediately(boolean unservo_immediately_)
   {
      this.unservo_immediately_ = unservo_immediately_;
   }

   public boolean getUnservoSlowly()
   {
      return unservo_slowly_;
   }

   public void setUnservoSlowly(boolean unservo_slowly_)
   {
      this.unservo_slowly_ = unservo_slowly_;
   }


}