/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.

##################################################################################
This file was generated from the following content:
(controller_msgs/MasterGainScaleControllerStatusMessage.msg)
##################################################################################
   # Whether the robot's gains are currently active in holding the controller's desireds
   bool is_robot_servoed

##################################################################################

 */
package controller_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

public class MasterGainScaleControllerStatusMessage implements ROS2Message<MasterGainScaleControllerStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MasterGainScaleControllerStatusMessage_";

   /**
      Whether the robot's gains are currently active in holding the controller's desireds
   */
   private boolean is_robot_servoed_;

   public MasterGainScaleControllerStatusMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_robot_servoed_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(is_robot_servoed_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      is_robot_servoed_ = buffer.readBoolean();

   }

   @Override
   public void set(MasterGainScaleControllerStatusMessage from)
   {
      is_robot_servoed_ = from.is_robot_servoed_;

   }

   public boolean getIsRobotServoed()
   {
      return is_robot_servoed_;
   }

   public void setIsRobotServoed(boolean is_robot_servoed_)
   {
      this.is_robot_servoed_ = is_robot_servoed_;
   }


}